sudo: false

language: node_js

node_js:
    - 10
    - 12
    - 13

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules

before_install:
    - npm config set spin false
    - npm config set progress false
    - npm install -g npm

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: kmHk0ZrL4wZSxRLUwNq1yLnUdeXp4nldqueu2PZz66D7T9zqGA2en1KN3Kmk/hr+fO1a2XY2JSVIhs5eBt39yY1fMMXkFI9cCphEDiJ8D1i6YosUAVaxnqK9ZYjE5WAahCJ/TARJx0YQVYH/XunOffd5sdbigK/5hm19GNvrTH9Qzbkv+pMrNfaMlJ8N4x8d8cv7oMFMMlsuMeJzgJ1x3sN6XUQFtCYp2QSm1lWyeiv5zIeVUcIU7tJOUwUm6+P3y4FVrKOHvpzKht48tHSdqqfiT6PVh9V4Rs4nxeWdzlVIl4nVf4imcybM7ztzmjONdRsETfnLVXALBwKjPYu+efhPa3KwPrwN8H9LijJhLyKgkInOuGYRmgtc9Wk1EV6/2tROvS6D45YMDmVVm0+kadY9icO2c/WcCZkelshnOoEGoPgzW8bl1yNeI+D5s+ZkimF4YRCLj4PJju+pSqJg2gHgyYljqbE4utj2UFSIM4BqLjoX7q9rzAq+yPVcD7h4LezJ45fGH13Q4kpTqvLfzY4ug0i23kdWtjGkcr2wCOfDrmICNuIbFMEpOweamKAKEjzDym3j2xzw+6h/rh6/Udqs31P9QijPs5rMRjyN17E/CIrskTvXFA2QyLPgSnYbWUM+J7maMOugAuotVNct5Y6zJVNBocNTTmn/XLl2ijU=
      on:
          node: 13
          repo: whizark/remark-preset
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: o/xp/8ozhSZL/vNzTm0JIQTbcknu6b59BkHEjmbBKE54NFObkSrrtPxbHL2Jlf6A/ebbG3bEz7PlB2Q3dMQ1LN2r6k7KG+5d8+UB23uO2ae5VbRxckvM4Lcs3Qi9DDBiuCs0lM2Gh/Uvp+Skf7ToabxtIsNFIYYGzoK9Rznbj1u3TSQ4NzPq+EMVjcsP0BrGZcjAgJCCvyZwreBhwIHN6qcuczx7G1dwJP6U+7fxknyOflhA+xoqTxerqp8iaeH2fltzC0mArL0oaRj1r2kDzM+am3gxsYbRJTlDcfxzzEN/Y1qcLVHz5sSGY8Hw3pRhrKW5aFLqN54OGBpLTmMBJ7Zps3yIhQcbc4fWESrXqVECZXraSIEYZnVN2wyP6ZoTBWhazALl/kRx8YzkJfrKy1qmwOYt5d/63M0IvMHZFc8/tB+eHDQjzrGOOdz2pW61XzMJOIQpe8ey/p693F59mW2ubqUpd1k5rgDrayODnhpxmo6gly2ZNQG4PpdI29nBk75weZMNsZQqos7RhL6qZi8zKOL5RTrxMZKs9IGIzkeHwoeWvmmaWYmeuk3T+/eDqDZUSNwLYFybPwshysO3gCiE3wiZqVmpLx2p5LGltokKfFC5Gu1dTdSrU/pxr1J85Y0+17YRmmb5pNTlhG7zM8wnLrVa2f8CvNBZxtDK6yE=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
